name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to S3
      run: |
        aws s3 sync ./frontend/dist/frontend/browser/ s3://example-app-mj/ --delete

  deploy-backend:
    runs-on: ubuntu-latest
    needs: deploy-frontend
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t my-backend ./backend

    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push my-backend

    - name: Deploy to EC2
      run: |
        scp -o StrictHostKeyChecking=no docker-compose.yml ubuntu@3.75.246.245:/home/ubuntu/
        ssh -o StrictHostKeyChecking=no ubuntu@3.75.246.245 "docker-compose up -d"
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
